/*
 * Proovid Electronic Verification
 * Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 
 *
 * The version of the OpenAPI document: v1
 * Contact: info@proovid.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Level;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DescriptionLevels
 */
public class DescriptionLevelsTest {
    private final DescriptionLevels model = new DescriptionLevels();

    /**
     * Model tests for DescriptionLevels
     */
    @Test
    public void testDescriptionLevels() {
        // TODO: test DescriptionLevels
    }

    /**
     * Test the property 'level1'
     */
    @Test
    public void level1Test() {
        // TODO: test level1
    }

    /**
     * Test the property 'level2'
     */
    @Test
    public void level2Test() {
        // TODO: test level2
    }

    /**
     * Test the property 'level3'
     */
    @Test
    public void level3Test() {
        // TODO: test level3
    }

    /**
     * Test the property 'level4'
     */
    @Test
    public void level4Test() {
        // TODO: test level4
    }

}
