/*
 * Proovid Electronic Verification
 * Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 
 *
 * The version of the OpenAPI document: v1
 * Contact: info@proovid.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.DocumentVerificationData;
import com.konfigthis.client.model.DocumentVerificationResult;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DocumentVerificationResponse
 */
public class DocumentVerificationResponseTest {
    private final DocumentVerificationResponse model = new DocumentVerificationResponse();

    /**
     * Model tests for DocumentVerificationResponse
     */
    @Test
    public void testDocumentVerificationResponse() {
        // TODO: test DocumentVerificationResponse
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'systemId'
     */
    @Test
    public void systemIdTest() {
        // TODO: test systemId
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'documentData'
     */
    @Test
    public void documentDataTest() {
        // TODO: test documentData
    }

    /**
     * Test the property 'documentResult'
     */
    @Test
    public void documentResultTest() {
        // TODO: test documentResult
    }

    /**
     * Test the property 'declinedReason'
     */
    @Test
    public void declinedReasonTest() {
        // TODO: test declinedReason
    }

    /**
     * Test the property 'declinedCodeProovid'
     */
    @Test
    public void declinedCodeProovidTest() {
        // TODO: test declinedCodeProovid
    }

}
