/*
 * Proovid Electronic Verification
 * Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 
 *
 * The version of the OpenAPI document: v1
 * Contact: info@proovid.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Geolocation
 */
public class GeolocationTest {
    private final Geolocation model = new Geolocation();

    /**
     * Model tests for Geolocation
     */
    @Test
    public void testGeolocation() {
        // TODO: test Geolocation
    }

    /**
     * Test the property 'host'
     */
    @Test
    public void hostTest() {
        // TODO: test host
    }

    /**
     * Test the property 'ip'
     */
    @Test
    public void ipTest() {
        // TODO: test ip
    }

    /**
     * Test the property 'rdns'
     */
    @Test
    public void rdnsTest() {
        // TODO: test rdns
    }

    /**
     * Test the property 'asn'
     */
    @Test
    public void asnTest() {
        // TODO: test asn
    }

    /**
     * Test the property 'isp'
     */
    @Test
    public void ispTest() {
        // TODO: test isp
    }

    /**
     * Test the property 'countryName'
     */
    @Test
    public void countryNameTest() {
        // TODO: test countryName
    }

    /**
     * Test the property 'countryCode'
     */
    @Test
    public void countryCodeTest() {
        // TODO: test countryCode
    }

    /**
     * Test the property 'regionName'
     */
    @Test
    public void regionNameTest() {
        // TODO: test regionName
    }

    /**
     * Test the property 'regionCode'
     */
    @Test
    public void regionCodeTest() {
        // TODO: test regionCode
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'postalCode'
     */
    @Test
    public void postalCodeTest() {
        // TODO: test postalCode
    }

    /**
     * Test the property 'continentName'
     */
    @Test
    public void continentNameTest() {
        // TODO: test continentName
    }

    /**
     * Test the property 'continentCode'
     */
    @Test
    public void continentCodeTest() {
        // TODO: test continentCode
    }

    /**
     * Test the property 'latitude'
     */
    @Test
    public void latitudeTest() {
        // TODO: test latitude
    }

    /**
     * Test the property 'longitude'
     */
    @Test
    public void longitudeTest() {
        // TODO: test longitude
    }

    /**
     * Test the property 'metroCode'
     */
    @Test
    public void metroCodeTest() {
        // TODO: test metroCode
    }

    /**
     * Test the property 'timezone'
     */
    @Test
    public void timezoneTest() {
        // TODO: test timezone
    }

}
