/*
 * Proovid Electronic Verification
 * Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 
 *
 * The version of the OpenAPI document: v1
 * Contact: info@proovid.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.EGender;
import com.konfigthis.client.model.EScore;
import com.konfigthis.client.model.EStatus;
import com.konfigthis.client.model.NaturalPersonAddressVerificationResponse;
import com.konfigthis.client.model.NaturalPersonAmlVerificationResponse;
import com.konfigthis.client.model.NaturalPersonDocumentVerificationResponse;
import com.konfigthis.client.model.NaturalPersonEconomicProfileResponse;
import com.konfigthis.client.model.NaturalPersonFaceVerificationResponse;
import com.konfigthis.client.model.NaturalPersonOccupationResponse;
import com.konfigthis.client.model.NaturalPersonOtherSourceOfIncomeResponse;
import com.konfigthis.client.model.NaturalPersonOtherSourceOfWealthResponse;
import com.konfigthis.client.model.RejectLabelType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for NaturalPersonInfoResponse
 */
public class NaturalPersonInfoResponseTest {
    private final NaturalPersonInfoResponse model = new NaturalPersonInfoResponse();

    /**
     * Model tests for NaturalPersonInfoResponse
     */
    @Test
    public void testNaturalPersonInfoResponse() {
        // TODO: test NaturalPersonInfoResponse
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'clientReferenceId'
     */
    @Test
    public void clientReferenceIdTest() {
        // TODO: test clientReferenceId
    }

    /**
     * Test the property 'creationDate'
     */
    @Test
    public void creationDateTest() {
        // TODO: test creationDate
    }

    /**
     * Test the property 'lastUpdatedDate'
     */
    @Test
    public void lastUpdatedDateTest() {
        // TODO: test lastUpdatedDate
    }

    /**
     * Test the property 'deletionDate'
     */
    @Test
    public void deletionDateTest() {
        // TODO: test deletionDate
    }

    /**
     * Test the property 'taxId'
     */
    @Test
    public void taxIdTest() {
        // TODO: test taxId
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'middleName'
     */
    @Test
    public void middleNameTest() {
        // TODO: test middleName
    }

    /**
     * Test the property 'legalName'
     */
    @Test
    public void legalNameTest() {
        // TODO: test legalName
    }

    /**
     * Test the property 'dateOfBirth'
     */
    @Test
    public void dateOfBirthTest() {
        // TODO: test dateOfBirth
    }

    /**
     * Test the property 'gender'
     */
    @Test
    public void genderTest() {
        // TODO: test gender
    }

    /**
     * Test the property 'countryBirth'
     */
    @Test
    public void countryBirthTest() {
        // TODO: test countryBirth
    }

    /**
     * Test the property 'countryResidence'
     */
    @Test
    public void countryResidenceTest() {
        // TODO: test countryResidence
    }

    /**
     * Test the property 'countryMainBusiness'
     */
    @Test
    public void countryMainBusinessTest() {
        // TODO: test countryMainBusiness
    }

    /**
     * Test the property 'nationality'
     */
    @Test
    public void nationalityTest() {
        // TODO: test nationality
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'emailTwo'
     */
    @Test
    public void emailTwoTest() {
        // TODO: test emailTwo
    }

    /**
     * Test the property 'mobilePhone'
     */
    @Test
    public void mobilePhoneTest() {
        // TODO: test mobilePhone
    }

    /**
     * Test the property 'mobilePhoneTwo'
     */
    @Test
    public void mobilePhoneTwoTest() {
        // TODO: test mobilePhoneTwo
    }

    /**
     * Test the property 'automaticallyUpdateNPRisk'
     */
    @Test
    public void automaticallyUpdateNPRiskTest() {
        // TODO: test automaticallyUpdateNPRisk
    }

    /**
     * Test the property 'riskLevel'
     */
    @Test
    public void riskLevelTest() {
        // TODO: test riskLevel
    }

    /**
     * Test the property 'riskLevelJustification'
     */
    @Test
    public void riskLevelJustificationTest() {
        // TODO: test riskLevelJustification
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'rejectLabels'
     */
    @Test
    public void rejectLabelsTest() {
        // TODO: test rejectLabels
    }

    /**
     * Test the property 'isFlagged'
     */
    @Test
    public void isFlaggedTest() {
        // TODO: test isFlagged
    }

    /**
     * Test the property 'comments'
     */
    @Test
    public void commentsTest() {
        // TODO: test comments
    }

    /**
     * Test the property 'economicProfile'
     */
    @Test
    public void economicProfileTest() {
        // TODO: test economicProfile
    }

    /**
     * Test the property 'documentVerification'
     */
    @Test
    public void documentVerificationTest() {
        // TODO: test documentVerification
    }

    /**
     * Test the property 'addressVerification'
     */
    @Test
    public void addressVerificationTest() {
        // TODO: test addressVerification
    }

    /**
     * Test the property 'faceVerification'
     */
    @Test
    public void faceVerificationTest() {
        // TODO: test faceVerification
    }

    /**
     * Test the property 'screeningVerification'
     */
    @Test
    public void screeningVerificationTest() {
        // TODO: test screeningVerification
    }

    /**
     * Test the property 'otherSourcesOfIncome'
     */
    @Test
    public void otherSourcesOfIncomeTest() {
        // TODO: test otherSourcesOfIncome
    }

    /**
     * Test the property 'otherSourcesOfWealth'
     */
    @Test
    public void otherSourcesOfWealthTest() {
        // TODO: test otherSourcesOfWealth
    }

    /**
     * Test the property 'industries'
     */
    @Test
    public void industriesTest() {
        // TODO: test industries
    }

}
