/*
 * Proovid Electronic Verification
 * Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 
 *
 * The version of the OpenAPI document: v1
 * Contact: info@proovid.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.NaturalPersonDocumentRequest;
import com.konfigthis.client.model.NaturalPersonIdDocumentRequest;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for NaturalPersonDocumentsRequest
 */
public class NaturalPersonDocumentsRequestTest {
    private final NaturalPersonDocumentsRequest model = new NaturalPersonDocumentsRequest();

    /**
     * Model tests for NaturalPersonDocumentsRequest
     */
    @Test
    public void testNaturalPersonDocumentsRequest() {
        // TODO: test NaturalPersonDocumentsRequest
    }

    /**
     * Test the property 'idDocument'
     */
    @Test
    public void idDocumentTest() {
        // TODO: test idDocument
    }

    /**
     * Test the property 'addressDocument'
     */
    @Test
    public void addressDocumentTest() {
        // TODO: test addressDocument
    }

}
