/*
 * Proovid Electronic Verification
 * Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 
 *
 * The version of the OpenAPI document: v1
 * Contact: info@proovid.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Error;
import com.konfigthis.client.model.Info;
import com.konfigthis.client.model.VerificationData;
import com.konfigthis.client.model.VerificationResult;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ShuftiAddressDataResponse
 */
public class ShuftiAddressDataResponseTest {
    private final ShuftiAddressDataResponse model = new ShuftiAddressDataResponse();

    /**
     * Model tests for ShuftiAddressDataResponse
     */
    @Test
    public void testShuftiAddressDataResponse() {
        // TODO: test ShuftiAddressDataResponse
    }

    /**
     * Test the property 'info'
     */
    @Test
    public void infoTest() {
        // TODO: test info
    }

    /**
     * Test the property 'reference'
     */
    @Test
    public void referenceTest() {
        // TODO: test reference
    }

    /**
     * Test the property 'event'
     */
    @Test
    public void eventTest() {
        // TODO: test event
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'verificationData'
     */
    @Test
    public void verificationDataTest() {
        // TODO: test verificationData
    }

    /**
     * Test the property 'verificationResult'
     */
    @Test
    public void verificationResultTest() {
        // TODO: test verificationResult
    }

    /**
     * Test the property 'declinedReason'
     */
    @Test
    public void declinedReasonTest() {
        // TODO: test declinedReason
    }

    /**
     * Test the property 'declinedCodes'
     */
    @Test
    public void declinedCodesTest() {
        // TODO: test declinedCodes
    }

}
