/*
 * Proovid Electronic Verification
 * Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 
 *
 * The version of the OpenAPI document: v1
 * Contact: info@proovid.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ShuftiAddressResultResponse
 */
public class ShuftiAddressResultResponseTest {
    private final ShuftiAddressResultResponse model = new ShuftiAddressResultResponse();

    /**
     * Model tests for ShuftiAddressResultResponse
     */
    @Test
    public void testShuftiAddressResultResponse() {
        // TODO: test ShuftiAddressResultResponse
    }

    /**
     * Test the property 'issueDate'
     */
    @Test
    public void issueDateTest() {
        // TODO: test issueDate
    }

    /**
     * Test the property 'selectedType'
     */
    @Test
    public void selectedTypeTest() {
        // TODO: test selectedType
    }

    /**
     * Test the property 'addressDocumentCountry'
     */
    @Test
    public void addressDocumentCountryTest() {
        // TODO: test addressDocumentCountry
    }

    /**
     * Test the property 'addressDocumentMustNotBeExpired'
     */
    @Test
    public void addressDocumentMustNotBeExpiredTest() {
        // TODO: test addressDocumentMustNotBeExpired
    }

    /**
     * Test the property 'fullAddress'
     */
    @Test
    public void fullAddressTest() {
        // TODO: test fullAddress
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'addressDocumentVisibility'
     */
    @Test
    public void addressDocumentVisibilityTest() {
        // TODO: test addressDocumentVisibility
    }

    /**
     * Test the property 'addressDocument'
     */
    @Test
    public void addressDocumentTest() {
        // TODO: test addressDocument
    }

    /**
     * Test the property 'addressDocumentProof'
     */
    @Test
    public void addressDocumentProofTest() {
        // TODO: test addressDocumentProof
    }

}
