/*
 * Proovid Electronic Verification
 * Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 
 *
 * The version of the OpenAPI document: v1
 * Contact: info@proovid.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.EGender;
import com.konfigthis.client.model.EScore;
import com.konfigthis.client.model.UpdateNaturalPersonEconomicProfileRequest;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for UpdateNaturalPersonInfoRequest
 */
public class UpdateNaturalPersonInfoRequestTest {
    private final UpdateNaturalPersonInfoRequest model = new UpdateNaturalPersonInfoRequest();

    /**
     * Model tests for UpdateNaturalPersonInfoRequest
     */
    @Test
    public void testUpdateNaturalPersonInfoRequest() {
        // TODO: test UpdateNaturalPersonInfoRequest
    }

    /**
     * Test the property 'clientReferenceId'
     */
    @Test
    public void clientReferenceIdTest() {
        // TODO: test clientReferenceId
    }

    /**
     * Test the property 'taxId'
     */
    @Test
    public void taxIdTest() {
        // TODO: test taxId
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'middleName'
     */
    @Test
    public void middleNameTest() {
        // TODO: test middleName
    }

    /**
     * Test the property 'legalName'
     */
    @Test
    public void legalNameTest() {
        // TODO: test legalName
    }

    /**
     * Test the property 'dateOfBirth'
     */
    @Test
    public void dateOfBirthTest() {
        // TODO: test dateOfBirth
    }

    /**
     * Test the property 'gender'
     */
    @Test
    public void genderTest() {
        // TODO: test gender
    }

    /**
     * Test the property 'countryBirth'
     */
    @Test
    public void countryBirthTest() {
        // TODO: test countryBirth
    }

    /**
     * Test the property 'countryResidence'
     */
    @Test
    public void countryResidenceTest() {
        // TODO: test countryResidence
    }

    /**
     * Test the property 'countryMainBusiness'
     */
    @Test
    public void countryMainBusinessTest() {
        // TODO: test countryMainBusiness
    }

    /**
     * Test the property 'nationality'
     */
    @Test
    public void nationalityTest() {
        // TODO: test nationality
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'emailTwo'
     */
    @Test
    public void emailTwoTest() {
        // TODO: test emailTwo
    }

    /**
     * Test the property 'mobilePhone'
     */
    @Test
    public void mobilePhoneTest() {
        // TODO: test mobilePhone
    }

    /**
     * Test the property 'mobilePhoneTwo'
     */
    @Test
    public void mobilePhoneTwoTest() {
        // TODO: test mobilePhoneTwo
    }

    /**
     * Test the property 'automaticallyUpdateNPRisk'
     */
    @Test
    public void automaticallyUpdateNPRiskTest() {
        // TODO: test automaticallyUpdateNPRisk
    }

    /**
     * Test the property 'riskLevel'
     */
    @Test
    public void riskLevelTest() {
        // TODO: test riskLevel
    }

    /**
     * Test the property 'riskLevelJustification'
     */
    @Test
    public void riskLevelJustificationTest() {
        // TODO: test riskLevelJustification
    }

    /**
     * Test the property 'isFlagged'
     */
    @Test
    public void isFlaggedTest() {
        // TODO: test isFlagged
    }

    /**
     * Test the property 'comments'
     */
    @Test
    public void commentsTest() {
        // TODO: test comments
    }

    /**
     * Test the property 'economicProfile'
     */
    @Test
    public void economicProfileTest() {
        // TODO: test economicProfile
    }

}
