/*
 * Proovid Electronic Verification
 * Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 
 *
 * The version of the OpenAPI document: v1
 * Contact: info@proovid.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.EMoneyRange;
import com.konfigthis.client.model.ESourceOfIncomeAnswers;
import com.konfigthis.client.model.ESourceOfWealthAnswers;
import com.konfigthis.client.model.EWealthRange;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for UpdateNaturalPersonEconomicProfileRequest
 */
public class UpdateNaturalPersonEconomicProfileRequestTest {
    private final UpdateNaturalPersonEconomicProfileRequest model = new UpdateNaturalPersonEconomicProfileRequest();

    /**
     * Model tests for UpdateNaturalPersonEconomicProfileRequest
     */
    @Test
    public void testUpdateNaturalPersonEconomicProfileRequest() {
        // TODO: test UpdateNaturalPersonEconomicProfileRequest
    }

    /**
     * Test the property 'mainBusinessActivities'
     */
    @Test
    public void mainBusinessActivitiesTest() {
        // TODO: test mainBusinessActivities
    }

    /**
     * Test the property 'sizeOfAnnualIncome'
     */
    @Test
    public void sizeOfAnnualIncomeTest() {
        // TODO: test sizeOfAnnualIncome
    }

    /**
     * Test the property 'sizeOfAnnualIncomeMin'
     */
    @Test
    public void sizeOfAnnualIncomeMinTest() {
        // TODO: test sizeOfAnnualIncomeMin
    }

    /**
     * Test the property 'sizeOfAnnualIncomeMax'
     */
    @Test
    public void sizeOfAnnualIncomeMaxTest() {
        // TODO: test sizeOfAnnualIncomeMax
    }

    /**
     * Test the property 'mainSourceOfIncome'
     */
    @Test
    public void mainSourceOfIncomeTest() {
        // TODO: test mainSourceOfIncome
    }

    /**
     * Test the property 'sizeOfWealth'
     */
    @Test
    public void sizeOfWealthTest() {
        // TODO: test sizeOfWealth
    }

    /**
     * Test the property 'sizeOfWealthMin'
     */
    @Test
    public void sizeOfWealthMinTest() {
        // TODO: test sizeOfWealthMin
    }

    /**
     * Test the property 'sizeOfWealthMax'
     */
    @Test
    public void sizeOfWealthMaxTest() {
        // TODO: test sizeOfWealthMax
    }

    /**
     * Test the property 'isHnwi'
     */
    @Test
    public void isHnwiTest() {
        // TODO: test isHnwi
    }

    /**
     * Test the property 'sourceOfWealth'
     */
    @Test
    public void sourceOfWealthTest() {
        // TODO: test sourceOfWealth
    }

    /**
     * Test the property 'expectedOriginOfOutgoingFunds'
     */
    @Test
    public void expectedOriginOfOutgoingFundsTest() {
        // TODO: test expectedOriginOfOutgoingFunds
    }

    /**
     * Test the property 'expectedOriginOfIncomingFunds'
     */
    @Test
    public void expectedOriginOfIncomingFundsTest() {
        // TODO: test expectedOriginOfIncomingFunds
    }

    /**
     * Test the property 'natureOfTransaction'
     */
    @Test
    public void natureOfTransactionTest() {
        // TODO: test natureOfTransaction
    }

    /**
     * Test the property 'anticipatedAccountTurnOver'
     */
    @Test
    public void anticipatedAccountTurnOverTest() {
        // TODO: test anticipatedAccountTurnOver
    }

    /**
     * Test the property 'anticipatedAccountTurnOverMin'
     */
    @Test
    public void anticipatedAccountTurnOverMinTest() {
        // TODO: test anticipatedAccountTurnOverMin
    }

    /**
     * Test the property 'anticipatedAccountTurnOverMax'
     */
    @Test
    public void anticipatedAccountTurnOverMaxTest() {
        // TODO: test anticipatedAccountTurnOverMax
    }

    /**
     * Test the property 'purposeOfBusinessRelationship'
     */
    @Test
    public void purposeOfBusinessRelationshipTest() {
        // TODO: test purposeOfBusinessRelationship
    }

}
