/*
 * Proovid Electronic Verification
 * Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 
 *
 * The version of the OpenAPI document: v1
 * Contact: info@proovid.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.BaseResponse;
import com.konfigthis.client.model.StringBaseResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for UpdateNaturalPersonDocumentsDataSaveResult
 */
public class UpdateNaturalPersonDocumentsDataSaveResultTest {
    private final UpdateNaturalPersonDocumentsDataSaveResult model = new UpdateNaturalPersonDocumentsDataSaveResult();

    /**
     * Model tests for UpdateNaturalPersonDocumentsDataSaveResult
     */
    @Test
    public void testUpdateNaturalPersonDocumentsDataSaveResult() {
        // TODO: test UpdateNaturalPersonDocumentsDataSaveResult
    }

    /**
     * Test the property 'idDocumentSaved'
     */
    @Test
    public void idDocumentSavedTest() {
        // TODO: test idDocumentSaved
    }

    /**
     * Test the property 'faceSaved'
     */
    @Test
    public void faceSavedTest() {
        // TODO: test faceSaved
    }

    /**
     * Test the property 'livenessCheckURL'
     */
    @Test
    public void livenessCheckURLTest() {
        // TODO: test livenessCheckURL
    }

    /**
     * Test the property 'addressDocumentSaved'
     */
    @Test
    public void addressDocumentSavedTest() {
        // TODO: test addressDocumentSaved
    }

    /**
     * Test the property 'verificationStarted'
     */
    @Test
    public void verificationStartedTest() {
        // TODO: test verificationStarted
    }

    /**
     * Test the property 'allSucceeded'
     */
    @Test
    public void allSucceededTest() {
        // TODO: test allSucceeded
    }

}
