/*
 * Proovid Electronic Verification
 * Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 
 *
 * The version of the OpenAPI document: v1
 * Contact: info@proovid.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AddressDocumentVerificationResult;
import com.konfigthis.client.model.DescriptionLevels;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * AddressVerificationResult
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class AddressVerificationResult {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_REFERENCE = "reference";
  @SerializedName(SERIALIZED_NAME_REFERENCE)
  private String reference;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private Integer status;

  public static final String SERIALIZED_NAME_VERIFICATION_LEVEL = "verificationLevel";
  @SerializedName(SERIALIZED_NAME_VERIFICATION_LEVEL)
  private Integer verificationLevel;

  public static final String SERIALIZED_NAME_LEVELS = "levels";
  @SerializedName(SERIALIZED_NAME_LEVELS)
  private DescriptionLevels levels;

  public static final String SERIALIZED_NAME_DOCUMENT_VERIFICATION = "documentVerification";
  @SerializedName(SERIALIZED_NAME_DOCUMENT_VERIFICATION)
  private AddressDocumentVerificationResult documentVerification;

  public static final String SERIALIZED_NAME_USER_VERIFICATION_URL = "userVerificationUrl";
  @SerializedName(SERIALIZED_NAME_USER_VERIFICATION_URL)
  private String userVerificationUrl;

  public static final String SERIALIZED_NAME_QR_CODE = "qrCode";
  @SerializedName(SERIALIZED_NAME_QR_CODE)
  private String qrCode;

  public static final String SERIALIZED_NAME_CREATION_TIME = "creationTime";
  @SerializedName(SERIALIZED_NAME_CREATION_TIME)
  private OffsetDateTime creationTime;

  public static final String SERIALIZED_NAME_ERROR = "error";
  @SerializedName(SERIALIZED_NAME_ERROR)
  private String error;

  public AddressVerificationResult() {
  }

  public AddressVerificationResult id(Long id) {
    
    
    
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    
    
    
    this.id = id;
  }


  public AddressVerificationResult reference(String reference) {
    
    
    
    
    this.reference = reference;
    return this;
  }

   /**
   * Get reference
   * @return reference
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getReference() {
    return reference;
  }


  public void setReference(String reference) {
    
    
    
    this.reference = reference;
  }


  public AddressVerificationResult status(Integer status) {
    
    
    
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getStatus() {
    return status;
  }


  public void setStatus(Integer status) {
    
    
    
    this.status = status;
  }


  public AddressVerificationResult verificationLevel(Integer verificationLevel) {
    
    
    
    
    this.verificationLevel = verificationLevel;
    return this;
  }

   /**
   * Get verificationLevel
   * @return verificationLevel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getVerificationLevel() {
    return verificationLevel;
  }


  public void setVerificationLevel(Integer verificationLevel) {
    
    
    
    this.verificationLevel = verificationLevel;
  }


  public AddressVerificationResult levels(DescriptionLevels levels) {
    
    
    
    
    this.levels = levels;
    return this;
  }

   /**
   * Get levels
   * @return levels
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DescriptionLevels getLevels() {
    return levels;
  }


  public void setLevels(DescriptionLevels levels) {
    
    
    
    this.levels = levels;
  }


  public AddressVerificationResult documentVerification(AddressDocumentVerificationResult documentVerification) {
    
    
    
    
    this.documentVerification = documentVerification;
    return this;
  }

   /**
   * Get documentVerification
   * @return documentVerification
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AddressDocumentVerificationResult getDocumentVerification() {
    return documentVerification;
  }


  public void setDocumentVerification(AddressDocumentVerificationResult documentVerification) {
    
    
    
    this.documentVerification = documentVerification;
  }


  public AddressVerificationResult userVerificationUrl(String userVerificationUrl) {
    
    
    
    
    this.userVerificationUrl = userVerificationUrl;
    return this;
  }

   /**
   * Get userVerificationUrl
   * @return userVerificationUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUserVerificationUrl() {
    return userVerificationUrl;
  }


  public void setUserVerificationUrl(String userVerificationUrl) {
    
    
    
    this.userVerificationUrl = userVerificationUrl;
  }


  public AddressVerificationResult qrCode(String qrCode) {
    
    
    
    
    this.qrCode = qrCode;
    return this;
  }

   /**
   * Get qrCode
   * @return qrCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getQrCode() {
    return qrCode;
  }


  public void setQrCode(String qrCode) {
    
    
    
    this.qrCode = qrCode;
  }


  public AddressVerificationResult creationTime(OffsetDateTime creationTime) {
    
    
    
    
    this.creationTime = creationTime;
    return this;
  }

   /**
   * Get creationTime
   * @return creationTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getCreationTime() {
    return creationTime;
  }


  public void setCreationTime(OffsetDateTime creationTime) {
    
    
    
    this.creationTime = creationTime;
  }


  public AddressVerificationResult error(String error) {
    
    
    
    
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getError() {
    return error;
  }


  public void setError(String error) {
    
    
    
    this.error = error;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the AddressVerificationResult instance itself
   */
  public AddressVerificationResult putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddressVerificationResult addressVerificationResult = (AddressVerificationResult) o;
    return Objects.equals(this.id, addressVerificationResult.id) &&
        Objects.equals(this.reference, addressVerificationResult.reference) &&
        Objects.equals(this.status, addressVerificationResult.status) &&
        Objects.equals(this.verificationLevel, addressVerificationResult.verificationLevel) &&
        Objects.equals(this.levels, addressVerificationResult.levels) &&
        Objects.equals(this.documentVerification, addressVerificationResult.documentVerification) &&
        Objects.equals(this.userVerificationUrl, addressVerificationResult.userVerificationUrl) &&
        Objects.equals(this.qrCode, addressVerificationResult.qrCode) &&
        Objects.equals(this.creationTime, addressVerificationResult.creationTime) &&
        Objects.equals(this.error, addressVerificationResult.error)&&
        Objects.equals(this.additionalProperties, addressVerificationResult.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, reference, status, verificationLevel, levels, documentVerification, userVerificationUrl, qrCode, creationTime, error, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddressVerificationResult {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    verificationLevel: ").append(toIndentedString(verificationLevel)).append("\n");
    sb.append("    levels: ").append(toIndentedString(levels)).append("\n");
    sb.append("    documentVerification: ").append(toIndentedString(documentVerification)).append("\n");
    sb.append("    userVerificationUrl: ").append(toIndentedString(userVerificationUrl)).append("\n");
    sb.append("    qrCode: ").append(toIndentedString(qrCode)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("reference");
    openapiFields.add("status");
    openapiFields.add("verificationLevel");
    openapiFields.add("levels");
    openapiFields.add("documentVerification");
    openapiFields.add("userVerificationUrl");
    openapiFields.add("qrCode");
    openapiFields.add("creationTime");
    openapiFields.add("error");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to AddressVerificationResult
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!AddressVerificationResult.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AddressVerificationResult is not found in the empty JSON string", AddressVerificationResult.openapiRequiredFields.toString()));
        }
      }
      if (!jsonObj.get("reference").isJsonNull() && (jsonObj.get("reference") != null && !jsonObj.get("reference").isJsonNull()) && !jsonObj.get("reference").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `reference` to be a primitive type in the JSON string but got `%s`", jsonObj.get("reference").toString()));
      }
      // validate the optional field `levels`
      if (jsonObj.get("levels") != null && !jsonObj.get("levels").isJsonNull()) {
        DescriptionLevels.validateJsonObject(jsonObj.getAsJsonObject("levels"));
      }
      // validate the optional field `documentVerification`
      if (jsonObj.get("documentVerification") != null && !jsonObj.get("documentVerification").isJsonNull()) {
        AddressDocumentVerificationResult.validateJsonObject(jsonObj.getAsJsonObject("documentVerification"));
      }
      if (!jsonObj.get("userVerificationUrl").isJsonNull() && (jsonObj.get("userVerificationUrl") != null && !jsonObj.get("userVerificationUrl").isJsonNull()) && !jsonObj.get("userVerificationUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `userVerificationUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("userVerificationUrl").toString()));
      }
      if (!jsonObj.get("qrCode").isJsonNull() && (jsonObj.get("qrCode") != null && !jsonObj.get("qrCode").isJsonNull()) && !jsonObj.get("qrCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `qrCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("qrCode").toString()));
      }
      if (!jsonObj.get("error").isJsonNull() && (jsonObj.get("error") != null && !jsonObj.get("error").isJsonNull()) && !jsonObj.get("error").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `error` to be a primitive type in the JSON string but got `%s`", jsonObj.get("error").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AddressVerificationResult.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AddressVerificationResult' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AddressVerificationResult> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AddressVerificationResult.class));

       return (TypeAdapter<T>) new TypeAdapter<AddressVerificationResult>() {
           @Override
           public void write(JsonWriter out, AddressVerificationResult value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public AddressVerificationResult read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             AddressVerificationResult instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AddressVerificationResult given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AddressVerificationResult
  * @throws IOException if the JSON string is invalid with respect to AddressVerificationResult
  */
  public static AddressVerificationResult fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AddressVerificationResult.class);
  }

 /**
  * Convert an instance of AddressVerificationResult to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

