/*
 * Proovid Electronic Verification
 * Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 
 *
 * The version of the OpenAPI document: v1
 * Contact: info@proovid.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Level;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * DescriptionLevels
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class DescriptionLevels {
  public static final String SERIALIZED_NAME_LEVEL1 = "level1";
  @SerializedName(SERIALIZED_NAME_LEVEL1)
  private Level level1;

  public static final String SERIALIZED_NAME_LEVEL2 = "level2";
  @SerializedName(SERIALIZED_NAME_LEVEL2)
  private Level level2;

  public static final String SERIALIZED_NAME_LEVEL3 = "level3";
  @SerializedName(SERIALIZED_NAME_LEVEL3)
  private Level level3;

  public static final String SERIALIZED_NAME_LEVEL4 = "level4";
  @SerializedName(SERIALIZED_NAME_LEVEL4)
  private Level level4;

  public DescriptionLevels() {
  }

  public DescriptionLevels level1(Level level1) {
    
    
    
    
    this.level1 = level1;
    return this;
  }

   /**
   * Get level1
   * @return level1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Level getLevel1() {
    return level1;
  }


  public void setLevel1(Level level1) {
    
    
    
    this.level1 = level1;
  }


  public DescriptionLevels level2(Level level2) {
    
    
    
    
    this.level2 = level2;
    return this;
  }

   /**
   * Get level2
   * @return level2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Level getLevel2() {
    return level2;
  }


  public void setLevel2(Level level2) {
    
    
    
    this.level2 = level2;
  }


  public DescriptionLevels level3(Level level3) {
    
    
    
    
    this.level3 = level3;
    return this;
  }

   /**
   * Get level3
   * @return level3
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Level getLevel3() {
    return level3;
  }


  public void setLevel3(Level level3) {
    
    
    
    this.level3 = level3;
  }


  public DescriptionLevels level4(Level level4) {
    
    
    
    
    this.level4 = level4;
    return this;
  }

   /**
   * Get level4
   * @return level4
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Level getLevel4() {
    return level4;
  }


  public void setLevel4(Level level4) {
    
    
    
    this.level4 = level4;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the DescriptionLevels instance itself
   */
  public DescriptionLevels putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DescriptionLevels descriptionLevels = (DescriptionLevels) o;
    return Objects.equals(this.level1, descriptionLevels.level1) &&
        Objects.equals(this.level2, descriptionLevels.level2) &&
        Objects.equals(this.level3, descriptionLevels.level3) &&
        Objects.equals(this.level4, descriptionLevels.level4)&&
        Objects.equals(this.additionalProperties, descriptionLevels.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(level1, level2, level3, level4, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DescriptionLevels {\n");
    sb.append("    level1: ").append(toIndentedString(level1)).append("\n");
    sb.append("    level2: ").append(toIndentedString(level2)).append("\n");
    sb.append("    level3: ").append(toIndentedString(level3)).append("\n");
    sb.append("    level4: ").append(toIndentedString(level4)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("level1");
    openapiFields.add("level2");
    openapiFields.add("level3");
    openapiFields.add("level4");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to DescriptionLevels
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!DescriptionLevels.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DescriptionLevels is not found in the empty JSON string", DescriptionLevels.openapiRequiredFields.toString()));
        }
      }
      // validate the optional field `level1`
      if (jsonObj.get("level1") != null && !jsonObj.get("level1").isJsonNull()) {
        Level.validateJsonObject(jsonObj.getAsJsonObject("level1"));
      }
      // validate the optional field `level2`
      if (jsonObj.get("level2") != null && !jsonObj.get("level2").isJsonNull()) {
        Level.validateJsonObject(jsonObj.getAsJsonObject("level2"));
      }
      // validate the optional field `level3`
      if (jsonObj.get("level3") != null && !jsonObj.get("level3").isJsonNull()) {
        Level.validateJsonObject(jsonObj.getAsJsonObject("level3"));
      }
      // validate the optional field `level4`
      if (jsonObj.get("level4") != null && !jsonObj.get("level4").isJsonNull()) {
        Level.validateJsonObject(jsonObj.getAsJsonObject("level4"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DescriptionLevels.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DescriptionLevels' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DescriptionLevels> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DescriptionLevels.class));

       return (TypeAdapter<T>) new TypeAdapter<DescriptionLevels>() {
           @Override
           public void write(JsonWriter out, DescriptionLevels value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public DescriptionLevels read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             DescriptionLevels instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of DescriptionLevels given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of DescriptionLevels
  * @throws IOException if the JSON string is invalid with respect to DescriptionLevels
  */
  public static DescriptionLevels fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DescriptionLevels.class);
  }

 /**
  * Convert an instance of DescriptionLevels to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

