/*
 * Proovid Electronic Verification
 * Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 
 *
 * The version of the OpenAPI document: v1
 * Contact: info@proovid.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.DocumentImages;
import com.konfigthis.client.model.SumSubVerificationResponse;
import com.konfigthis.client.model.UpdateNaturalPersonDocumentsDataSaveResult;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * UpdateNaturalPersonDocumentsResponse
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class UpdateNaturalPersonDocumentsResponse {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_CLIENT_REFERENCE_ID = "clientReferenceId";
  @SerializedName(SERIALIZED_NAME_CLIENT_REFERENCE_ID)
  private String clientReferenceId;

  public static final String SERIALIZED_NAME_DATA_SAVE_RESPONSES = "dataSaveResponses";
  @SerializedName(SERIALIZED_NAME_DATA_SAVE_RESPONSES)
  private UpdateNaturalPersonDocumentsDataSaveResult dataSaveResponses;

  public static final String SERIALIZED_NAME_VERIFICATION = "verification";
  @SerializedName(SERIALIZED_NAME_VERIFICATION)
  private SumSubVerificationResponse verification;

  public static final String SERIALIZED_NAME_DOCUMENT_IMAGES = "documentImages";
  @SerializedName(SERIALIZED_NAME_DOCUMENT_IMAGES)
  private DocumentImages documentImages;

  public UpdateNaturalPersonDocumentsResponse() {
  }

  public UpdateNaturalPersonDocumentsResponse id(Long id) {
    
    
    
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    
    
    
    this.id = id;
  }


  public UpdateNaturalPersonDocumentsResponse clientReferenceId(String clientReferenceId) {
    
    
    
    
    this.clientReferenceId = clientReferenceId;
    return this;
  }

   /**
   * Get clientReferenceId
   * @return clientReferenceId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getClientReferenceId() {
    return clientReferenceId;
  }


  public void setClientReferenceId(String clientReferenceId) {
    
    
    
    this.clientReferenceId = clientReferenceId;
  }


  public UpdateNaturalPersonDocumentsResponse dataSaveResponses(UpdateNaturalPersonDocumentsDataSaveResult dataSaveResponses) {
    
    
    
    
    this.dataSaveResponses = dataSaveResponses;
    return this;
  }

   /**
   * Get dataSaveResponses
   * @return dataSaveResponses
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public UpdateNaturalPersonDocumentsDataSaveResult getDataSaveResponses() {
    return dataSaveResponses;
  }


  public void setDataSaveResponses(UpdateNaturalPersonDocumentsDataSaveResult dataSaveResponses) {
    
    
    
    this.dataSaveResponses = dataSaveResponses;
  }


  public UpdateNaturalPersonDocumentsResponse verification(SumSubVerificationResponse verification) {
    
    
    
    
    this.verification = verification;
    return this;
  }

   /**
   * Get verification
   * @return verification
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public SumSubVerificationResponse getVerification() {
    return verification;
  }


  public void setVerification(SumSubVerificationResponse verification) {
    
    
    
    this.verification = verification;
  }


  public UpdateNaturalPersonDocumentsResponse documentImages(DocumentImages documentImages) {
    
    
    
    
    this.documentImages = documentImages;
    return this;
  }

   /**
   * Get documentImages
   * @return documentImages
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DocumentImages getDocumentImages() {
    return documentImages;
  }


  public void setDocumentImages(DocumentImages documentImages) {
    
    
    
    this.documentImages = documentImages;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the UpdateNaturalPersonDocumentsResponse instance itself
   */
  public UpdateNaturalPersonDocumentsResponse putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateNaturalPersonDocumentsResponse updateNaturalPersonDocumentsResponse = (UpdateNaturalPersonDocumentsResponse) o;
    return Objects.equals(this.id, updateNaturalPersonDocumentsResponse.id) &&
        Objects.equals(this.clientReferenceId, updateNaturalPersonDocumentsResponse.clientReferenceId) &&
        Objects.equals(this.dataSaveResponses, updateNaturalPersonDocumentsResponse.dataSaveResponses) &&
        Objects.equals(this.verification, updateNaturalPersonDocumentsResponse.verification) &&
        Objects.equals(this.documentImages, updateNaturalPersonDocumentsResponse.documentImages)&&
        Objects.equals(this.additionalProperties, updateNaturalPersonDocumentsResponse.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, clientReferenceId, dataSaveResponses, verification, documentImages, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateNaturalPersonDocumentsResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    clientReferenceId: ").append(toIndentedString(clientReferenceId)).append("\n");
    sb.append("    dataSaveResponses: ").append(toIndentedString(dataSaveResponses)).append("\n");
    sb.append("    verification: ").append(toIndentedString(verification)).append("\n");
    sb.append("    documentImages: ").append(toIndentedString(documentImages)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("clientReferenceId");
    openapiFields.add("dataSaveResponses");
    openapiFields.add("verification");
    openapiFields.add("documentImages");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to UpdateNaturalPersonDocumentsResponse
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!UpdateNaturalPersonDocumentsResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UpdateNaturalPersonDocumentsResponse is not found in the empty JSON string", UpdateNaturalPersonDocumentsResponse.openapiRequiredFields.toString()));
        }
      }
      if (!jsonObj.get("clientReferenceId").isJsonNull() && (jsonObj.get("clientReferenceId") != null && !jsonObj.get("clientReferenceId").isJsonNull()) && !jsonObj.get("clientReferenceId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `clientReferenceId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("clientReferenceId").toString()));
      }
      // validate the optional field `dataSaveResponses`
      if (jsonObj.get("dataSaveResponses") != null && !jsonObj.get("dataSaveResponses").isJsonNull()) {
        UpdateNaturalPersonDocumentsDataSaveResult.validateJsonObject(jsonObj.getAsJsonObject("dataSaveResponses"));
      }
      // validate the optional field `verification`
      if (jsonObj.get("verification") != null && !jsonObj.get("verification").isJsonNull()) {
        SumSubVerificationResponse.validateJsonObject(jsonObj.getAsJsonObject("verification"));
      }
      // validate the optional field `documentImages`
      if (jsonObj.get("documentImages") != null && !jsonObj.get("documentImages").isJsonNull()) {
        DocumentImages.validateJsonObject(jsonObj.getAsJsonObject("documentImages"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UpdateNaturalPersonDocumentsResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UpdateNaturalPersonDocumentsResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UpdateNaturalPersonDocumentsResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UpdateNaturalPersonDocumentsResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<UpdateNaturalPersonDocumentsResponse>() {
           @Override
           public void write(JsonWriter out, UpdateNaturalPersonDocumentsResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public UpdateNaturalPersonDocumentsResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             UpdateNaturalPersonDocumentsResponse instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of UpdateNaturalPersonDocumentsResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of UpdateNaturalPersonDocumentsResponse
  * @throws IOException if the JSON string is invalid with respect to UpdateNaturalPersonDocumentsResponse
  */
  public static UpdateNaturalPersonDocumentsResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdateNaturalPersonDocumentsResponse.class);
  }

 /**
  * Convert an instance of UpdateNaturalPersonDocumentsResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

